source "https://rubygems.org"

gem "sinatra"
gem "sinatra-activerecord"
gem 'sinatra-cross_origin'
gem "rake"
gem "bcrypt"
gem "sinatra-flash"
gem "i18n"
gem "rspec"
gem "capybara"
gem "factory_bot"
gem "database_cleaner"
gem "sidekiq"
gem "rack-cors"
gem "rack"
gem "rackup"
gem "rack-contrib"
gem "sqlite3"
gem 'dotenv'

group :production do
  gem "pg"
  gem "puma"
end
gem "webrick", "~> 1.9"
